# .travis.yml
sudo: false
language: ruby
rvm:
  - 2.2.1
cache: bundler
bundler_args: --without production development
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - bundle exec rake
before_script:
  - cp config/database.yml.example config/database.yml
  - psql -c 'create database quhac_test' -U postgres